title: MSA Architects
email: msa@helloample.com

# Build settings
markdown: kramdown

exclude:
  - lib
  - migrations
  - Rakefile
  - Gemfile*

collections_dir: collections
collections:
  case_studies:
    output: true
    permalink: /markets/(:links_to/:markets/:0/:slug)/:slug
  features:
    output: false
  markets:
    output: true
    permalink: /markets/:slug
    layout: market
  media_objects:
    output: false
  pages:
    output: true
    permalink: /:slug
  projects:
    output: false
  posts:
    output: true
    permalink: /design-thinking/:slug
  tags:
    output: false
  text_objects:
    output: false
  users:
    output: false

contentful:
  case_studies:
    id: case_study
    body: body
    belongs_to:
      - market
    has_many:
      blocks: [ media_object, text_object ]
    frontmatter:
      title: title
      subtitle: subtitle
      slug: slug
      image: image/url
  features:
    id: feature
    body: body
    frontmatter:
      title: title
      image: image/url
      href: href
  markets:
    id: market
    has_many:
      projects: [ projects ]
      case_studies: [ case_studies ]
    frontmatter:
      title: title
      slug: slug
  media_objects:
    id: media_object
    body: body
    frontmatter:
      title: title
      css: css
      image: image/url
  text_objects:
    id: text_object
    body: body
    frontmatter:
      title: title
      css: css
  pages:
    id: page
    body: body
    has_many:
      blocks: [ features, media_objects ]
    frontmatter:
      title: title
      subtitle: subtitle
      slug: slug
      permalink: slug
      image: image/url
      image_caption: image/description
      layout: layout
  posts:
    id: post
    body: body
    filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
    belongs_to:
      - user
    has_many:
      blocks: [ media_objects, text_objects ]
      tags: [tags]
    frontmatter:
      title: title
      slug: slug
      location: location
      published_at: published_at
      image: image/url
      slug: slug
      featured: featured
  projects:
    id: project
    frontmatter:
      title: title
      slug: slug
      image: image/url
  tags:
    id: tag
    frontmatter:
      title: title
      slug: slug
  users:
    id: user
    frontmatter:
      full_name: full_name
      slug: slug
      title: title
      image: image/url

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "case_studies"
    values:
      layout: case_study

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  sources:
  - _assets/stylesheets
  - _assets/javascripts

typekit_url: https://use.typekit.net/dow2fxa.css