title: MSA Design
email: msa@helloample.com
image: "http://via.placeholder.com/500x350?text=FPO"

# Build settings
markdown: kramdown

exclude:
  - lib
  - migrations
  - Rakefile
  - Gemfile*

include:
  - _redirects

keep_files:
  - assets
  - android-chrome-*
  - apple-touch-icon*
  - browserconfig.xml
  - favicon*
  - mstile-*
  - safari-pinned-tab.svg
  - site.webmanifest

collections_dir: collections
collections:
  awards:
    output: false
  careers:
    output: false
  case_studies:
    output: true
    permalink: /case-studies/:slug
  features:
    output: false
  markets:
    output: true
    permalink: /markets/:slug
  media_objects:
    output: false
  pages:
    output: true
    permalink: /:slug
  projects:
    output: true
    permalink: /markets/(:links_to/:markets/:0/:slug)/:slug
  posts:
    output: true
    permalink: /design-thinking/:slug
  tags:
    output: true
    permalink: /design-thinking/tags/:slug
  text_objects:
    output: false
  users:
    output: false

contentful:
  awards:
    id: award
    body: body
    frontmatter:
      title: title
      link: award_link
      date: date
  careers:
    id: career
    body: body
    frontmatter:
      title: title
      slug: slug
  case_studies:
    id: case_study
    body: body
    belongs_to:
      - market
    has_many:
      blocks: [ media_object, text_object ]
    frontmatter:
      title: title
      subtitle: subtitle
      slug: slug
      image: image/url
      image_caption: image/description
  features:
    id: feature
    body: body
    filename: "{{ title }}-{{ id }}"
    frontmatter:
      title: title
      image: image/url
      image_caption: image/description
      href: href
  markets:
    id: market
    body: body
    has_many:
      projects: [ projects ]
      case_studies: [ case_studies ]
    frontmatter:
      title: title
      slug: slug
      image: image/url
      image_caption: image/description
  media_objects:
    id: media_object
    body: body
    filename: "{{ title }}-{{ id }}"
    frontmatter:
      title: title
      css: css
      image: image/url
      image_caption: image/description
  text_objects:
    id: text_object
    body: body
    filename: "{{ title }}-{{ id }}"
    frontmatter:
      title: title
      css: css
  pages:
    id: page
    body: body
    has_many:
      blocks: [ features, media_objects, text_objects ]
    frontmatter:
      title: title
      subtitle: subtitle
      slug: slug
      permalink: slug
      image: image/url
      image_caption: image/description
      layout: layout
  posts:
    id: post
    body: body
    filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
    has_many:
      blocks: [ media_objects, text_objects ]
      tags: [ tags ]
    frontmatter:
      title: title
      slug: slug
      location: location
      published_at: published_at
      image: image/url
      image_caption: image/description
      slug: slug
      featured: featured
      author_first_name: author/first_name
      author_last_name: author/last_name
      author_slug: author/slug
      author_image: author/image/url
      author_credentials: author/credentials
      author_title: author/title
  projects:
    id: project
    body: body
    belongs_to:
      - market
    has_many:
      blocks: [features, media_objects, text_objects]
    frontmatter:
      title: title
      subtitle: subtitle
      slug: slug
      image: image/url
      image_caption: image/description
  tags:
    id: tag
    belongs_to:
      - post
    frontmatter:
      title: title
      slug: slug
      image: image/url
      image_caption: image/description
  users:
    id: user
    frontmatter:
      first_name: first_name
      last_name: last_name
      slug: slug
      title: title
      credentials: credentials
      image: image/url
      image_caption: image/description

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "markets"
    values:
      layout: market
  - scope:
      type: "case_studies"
    values:
      layout: case_study
  - scope:
      type: "projects"
    values:
      layout: project
  - scope:
      type: "posts"
    values:
      layout: post
  - scope:
      type: "tags"
    values:
      layout: tags

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  sources:
  - _assets/stylesheets
  - _assets/javascripts

# social links
linkedin_username: msa-architects
twitter_username: msaarch
facebook_username: MSAarchitects
instagram_username: msa_arch_ohio

image_sizes:
  cards_4x: "(min-width: 1200px) 278px, (min-width: 992px) 233px, (min-width: 768px) 173px, (min-width: 576px) 255px, 50vw"
  cards_2x: "(min-width: 1200px) 555px, (min-width: 992px) 465px, (min-width: 768px) 345px, (min-width: 576px) 510px, 100vw"
  blocks: "(min-width: 992px) 950px, (min-width: 768px) 700px, (min-width: 575px) 445px, 100vw"
  awards_blocks: "100vw"
  author_blocks: "(min-width: 768px) 254px, 173px"

typekit_url: https://use.typekit.net/dow2fxa.css
