title: MSA Architects
email: msa@helloample.com

# Build settings
markdown: kramdown

exclude:
  - lib
  - migrations
  - Rakefile
  - Gemfile*

collections_dir: collections
collections:
  media_objects:
    output: false
  features:
    output: false
  pages:
    output: true
    permalink: /:slug

contentful:
  content_types:
    features:
      id: feature
      body: body
      frontmatter:
        entry_mappings:
          title: title
          image: image/url
          href: href
    media_objects:
      id: media_object
      body: body
      frontmatter:
        entry_mappings:
          title: title
          image: image/url
    pages:
      id: page
      body: body
      has_many:
        blocks: [ features, media_objects ]
      frontmatter:
        entry_mappings:
          title: title
          subtitle: subtitle
          slug: slug
          permalink: slug
          layout: layout

defaults:
  - scope:
      path: ""
    values:
      layout: default

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  sources:
  - _assets/stylesheets
  - _assets/javascripts

typekit_url: https://use.typekit.net/dow2fxa.css