title: MSA Architects
email: msa@helloample.com

# Build settings
markdown: kramdown

collections_dir: collections
collections:
  pages:
    output: true
    permalink: /:slug

contentful:
  content_types:
    pages:
      id: page
      body: body
      frontmatter:
        entry_mappings:
          title: title
          slug: slug
          permalink: slug
          layout: layout

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  sources:
  - _assets/stylesheets
  - _assets/javascripts

typekit_url: https://use.typekit.net/dow2fxa.css